[package]
name = "cargo-compare"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.35"
# This version of cargo has some fixes to the new feature resolver that are missing from cargo 0.44.0.
cargo = { git = "https://github.com/rust-lang/cargo.git", rev = "0227f048fcb7c798026ede6cc20c92befc84c3a4" }
diffus = "0.9.1"
either = "1.6.1"
itertools = "0.9.0"
guppy = { path = "../../guppy" }
guppy-cmdlib = { path = "../../guppy-cmdlib", features = ["proptest010"] }
structopt = "0.3.21"
tempfile = "3.1.0"
once_cell = "1.5.2"
proptest = "0.10.1"
