[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>", "Brandon Williams <bmwill@fb.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.41"
clap = "2.33.3"
dialoguer = "0.7.1"
guppy = { version = "0.6.0", path = "../guppy", features = ["summaries"] }
guppy-cmdlib = { path = "../guppy-cmdlib" }
itertools = "0.9.0"
pathdiff = "0.2.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
structopt = "0.3.21"
toml_edit = "0.2.0"
